# Foot — configuración principal
# Incluye paleta sincronizada con Waybar (generada por foot_sync.sh)
include=~/.config/foot/colors.ini

[main]
font=MesloLGM Nerd Font Mono:size=10, JetBrainsMono Nerd Font:size=10, monospace:size=10
pad=8x8 center
dpi-aware=yes
initial-window-size-pixels=700x500
resize-delay-ms=100

[scrollback]
lines=1000

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=no
